# Generated by Django 3.0.8 on 2021-01-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='')),
                ('titulo', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name_plural': 'fotos',
            },
        ),
    ]
