# Generated by Django 3.0.8 on 2021-01-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='descripcion',
            field=models.TextField(blank=True, max_length=120),
        ),
    ]
