# Generated by Django 3.1.5 on 2021-01-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0002_auto_20210115_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesionalesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profesional_tipo', models.CharField(choices=[('Profesionales Especializados', 'Profesionales Especializados'), ('Profesionales Interdisciplinarios', 'Profesionales Interdisciplinarios')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='galeria',
        ),
    ]
