# Generated by Django 3.1.5 on 2021-01-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0003_auto_20210118_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionalesmodel',
            name='nombre',
            field=models.CharField(default='nahuel', max_length=50),
            preserve_default=False,
        ),
    ]
