# Generated by Django 3.1.5 on 2021-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0004_profesionalesmodel_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionalesmodel',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profesionalesmodel',
            name='mail',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profesionalesmodel',
            name='provincia',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profesionalesmodel',
            name='se_muestra',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profesionalesmodel',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profesionalesmodel',
            name='zona',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profesionalesmodel',
            name='Profesional_tipo',
            field=models.CharField(max_length=50),
        ),
    ]
