# Generated by Django 3.1.5 on 2021-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0005_auto_20210118_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionalesmodel',
            name='mail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
