# Generated by Django 3.1.5 on 2021-01-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0007_auto_20210118_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionalesmodel',
            name='Profesional_tipo',
            field=models.CharField(choices=[('Especializados', 'Especializados'), ('Interdisciplinarios', 'Interdisciplinarios')], max_length=50),
        ),
    ]
