# Generated by Django 3.1.5 on 2021-01-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0008_auto_20210118_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionalesmodel',
            name='descripcion_adicional',
            field=models.TextField(blank=True),
        ),
    ]
