# Generated by Django 3.1.5 on 2021-01-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0009_profesionalesmodel_descripcion_adicional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionalesmodel',
            name='Profesional_tipo',
            field=models.CharField(choices=[('Especializados', 'Especializados'), ('Interdisciplinarios', 'Interdisciplinarios')], max_length=200),
        ),
        migrations.AlterField(
            model_name='profesionalesmodel',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profesionalesmodel',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profesionalesmodel',
            name='provincia',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profesionalesmodel',
            name='telefono',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profesionalesmodel',
            name='zona',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
