# Generated by Django 3.1.5 on 2021-01-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0010_auto_20210118_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfesionalesModel',
        ),
    ]
