# Generated by Django 3.1.5 on 2021-01-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0012_sociossuscriptoresmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociossuscriptoresmodel',
            name='lugar_de_residencia',
            field=models.CharField(default='hola', max_length=100),
            preserve_default=False,
        ),
    ]
