# Generated by Django 3.1.5 on 2021-01-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0013_sociossuscriptoresmodel_lugar_de_residencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociossuscriptoresmodel',
            name='Socio_suscriptor',
            field=models.CharField(choices=[('Suscriptor', 'Suscriptor'), ('Socio', 'Socio')], default='Suscriptor', max_length=100),
        ),
    ]
