# Generated by Django 3.1.5 on 2021-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0015_auto_20210119_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociossuscriptoresmodel',
            name='Comprobante_de_pago',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
