# Generated by Django 3.1.5 on 2021-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0016_auto_20210119_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=100)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
