# Generated by Django 3.1.5 on 2021-01-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0017_contactomodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociossuscriptoresmodel',
            name='Comprobante_de_pago',
        ),
    ]
