# Generated by Django 3.1.5 on 2021-01-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewpage', '0018_remove_sociossuscriptoresmodel_comprobante_de_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociossuscriptoresmodel',
            name='tipo_de_persona',
            field=models.CharField(choices=[('Socio persona que tartamudea', 'Socio persona que tartamudea'), ('Socio Fonoaudiologa', 'Socio Fonoaudiologa'), ('Socio Padres', 'Socio Padres'), ('Socio Terapeuta', 'Socio Terapeuta'), ('Socio Hermano', 'Socio Hermano'), ('Padre o madre de una persona que tartamudea', 'Padre o madre de una persona que tartamudea'), ('Persona con disfluencia', 'Persona con disfluencia'), ('socio amigo', 'socio amigo'), ('Desconocido', 'Desconocido'), ('Profesional', 'Profesional')], default='Socio persona que tartamudea', max_length=100),
        ),
    ]
